# Generated by Django 2.1.3 on 2018-11-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=20)),
                ('list_date', models.DateTimeField(verbose_name='date listed')),
                ('baught', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
                ('items_sold', models.PositiveIntegerField(default=0)),
                ('items_baught', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.User'),
        ),
    ]
