# Generated by Django 2.1.3 on 2018-11-14 16:55

from django.db import migrations

import random, datetime

def seed_users(apps, schema_editor):
  User = apps.get_model('marketapp', 'User')
  for i in range(1, 101):
    rand_date = random.randint(1400000000, 1542208153)
    rand_date = datetime.datetime.fromtimestamp(rand_date)
    user = User(name = f"marketeer{i:03}",
                city = "Philadelphia",
                state = "PA",
                join_date = rand_date)
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_category_img_url'),
    ]

    operations = [
      migrations.RunPython(seed_users),
    ]
