# Generated by Django 2.1.3 on 2018-11-14 19:46

from django.db import migrations

def seed_categories(apps, schema_editor):
  Category = apps.get_model('marketapp', 'Category')
  categories = map_category_imgURL()
  for name, url in categories.items():
    category = Category(name = name, img_url = url)
    category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_auto_20181114_1155'),
    ]

    operations = [
      migrations.RunPython(seed_categories),
    ]

def map_category_imgURL():
  """all images are from pexels.com"""
  return {
    'furniture': 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?cs=srgb&dl=art-chairs-color-1350789.jpg&fm=jpg',
    'apparel': 'https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg?cs=srgb&dl=accessories-accessory-bag-322207.jpg&fm=jpg',
    'jewelry': 'https://images.pexels.com/photos/1453008/pexels-photo-1453008.jpeg?cs=srgb&dl=accessory-beads-bracelet-1453008.jpg&fm=jpg',
    'antique': 'https://images.pexels.com/photos/1095601/pexels-photo-1095601.jpeg?cs=srgb&dl=antique-classic-clock-1095601.jpg&fm=jpg',
    'electronics': 'https://images.pexels.com/photos/705164/computer-laptop-work-place-camera-705164.jpeg?cs=srgb&dl=camera-coffee-computer-705164.jpg&fm=jpg',
    'cell phones': 'https://images.pexels.com/photos/748598/pexels-photo-748598.jpeg?cs=srgb&dl=apple-devices-apple-watch-beautiful-748598.jpg&fm=jpg',
    'kitchen': 'https://images.pexels.com/photos/1271940/pexels-photo-1271940.jpeg?cs=srgb&dl=blur-close-up-coffee-maker-1271940.jpg&fm=jpg',
    'automotive': 'https://images.pexels.com/photos/627678/pexels-photo-627678.jpeg?cs=srgb&dl=action-asphalt-automobile-627678.jpg&fm=jpg',
    'baby/kid goods': 'https://images.pexels.com/photos/272056/pexels-photo-272056.jpeg?cs=srgb&dl=baby-bed-blue-272056.jpg&fm=jpg',
    'outdoors': 'https://images.pexels.com/photos/1230302/pexels-photo-1230302.jpeg?cs=srgb&dl=adult-adventure-backpack-1230302.jpg&fm=jpg',
    'collectible': 'https://images.pexels.com/photos/1181769/pexels-photo-1181769.jpeg?cs=srgb&dl=cd-collect-collection-1181769.jpg&fm=jpg',
    'hand crafted': 'https://images.pexels.com/photos/243059/pexels-photo-243059.jpeg?cs=srgb&dl=abstract-ancient-antique-243059.jpg&fm=jpg',
    'books': 'https://images.pexels.com/photos/768125/pexels-photo-768125.jpeg?cs=srgb&dl=book-book-bindings-books-768125.jpg&fm=jpg',
    'artwork': 'https://images.pexels.com/photos/383568/pexels-photo-383568.jpeg?cs=srgb&dl=art-black-and-white-collage-383568.jpg&fm=jpg',
  }
