# Generated by Django 2.1.3 on 2018-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0007_auto_20181115_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='baught_date',
            field=models.DateTimeField(null=True),
        ),
    ]
